print("Hello world!")
print("Hello\nworld!")
print("\\")
print("probando", "2 argumentos")
print("1 argumento", "2 argumentos", end=" - " )
print("3 argumentos")
print("David", "Guetta", sep="-")
print("My","name","is","Lezcouu", sep="_", end="*")
print("My","name","is","Lezcouu", sep="*", end="*\n")
print("Programming", "Essentials", "in", sep="***", end="...")
print("Python")
print(" "*4, "*")
print(" "*3,"*","*")
print(" "*2,"*"," ","*")
print(" ", "*", " "*3, "*")
print(" *"," "*5, "*")
print("***", " "*3, "***")
print(" "*1,"*", " "*3, "*")
print(" "*1,"*", " "*3, "*")
print(" "*1,"*", " "*3, "*")
print(" "*1,"*", " "*3, "*")
print(" "*1,"*"*7)